# Generated by Django 4.0.3 on 2022-04-10 07:45

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_validaccount_program_version'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgramVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=255)),
                ('exe', models.FileField(upload_to='program_versions')),
            ],
            managers=[
                ('programs', django.db.models.manager.Manager()),
            ],
        ),
        migrations.RemoveField(
            model_name='validaccount',
            name='program_version',
        ),
    ]
