# Generated by Django 4.0.3 on 2022-04-10 07:49

import backend.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_programversion_remove_validaccount_program_version'),
    ]

    operations = [
        migrations.AddField(
            model_name='programversion',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='validaccount',
            name='program_version',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='backend.programversion'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='programversion',
            name='exe',
            field=models.FileField(upload_to=backend.models.program_version_directory_path),
        ),
    ]
